In [2]:
# ==========================================
# PROJECT 1 - DATA CLEANING & PREPARATION
# ==========================================

import pandas as pd

# -----------------------------
# 1. Load Dataset
# -----------------------------
df = pd.read_csv('Dataset for Data Analytics - Sheet1.csv')

print("Dataset Loaded Successfully!\n")

# -----------------------------
# 2. Basic Information
# -----------------------------
print("Shape of Dataset:", df.shape)

print("\nData Types:")
print(df.dtypes)

print("\nFirst 5 Rows:")
display(df.head())

# -----------------------------
# 3. Missing Values
# -----------------------------
print("\nMissing Values:")
print(df.isnull().sum())

# -----------------------------
# 4. Duplicate Records
# -----------------------------
duplicates = df.duplicated().sum()

print("\nDuplicate Rows:", duplicates)

# Remove duplicates
df.drop_duplicates(inplace=True)

print("Duplicates Removed Successfully!")

# -----------------------------
# 5. Convert Date Column
# -----------------------------
df["Date"] = pd.to_datetime(df["Date"], errors="coerce")

# -----------------------------
# 6. Handle Missing Values
# -----------------------------
# CouponCode has missing values.
# Missing coupon means customer didn't use a coupon.

df["CouponCode"] = df["CouponCode"].fillna("No Coupon")

# -----------------------------
# 7. Verify Cleaning
# -----------------------------
print("\nRemaining Missing Values:")
print(df.isnull().sum())

print("\nDuplicate Rows After Cleaning:")
print(df.duplicated().sum())

print("\nDataset Shape After Cleaning:")
print(df.shape)

# -----------------------------
# 8. Final Data Types
# -----------------------------
print("\nUpdated Data Types:")
print(df.dtypes)

# -----------------------------
# 9. Save Cleaned Dataset
# -----------------------------
output_file = "cleaned_dataset.csv"

df.to_csv(output_file, index=False)

print(f"\nCleaned dataset saved as '{output_file}'")

# -----------------------------
# 10. Preview Cleaned Data
# -----------------------------
display(df.head())

Dataset Loaded Successfully!

Shape of Dataset: (1200, 14)

Data Types:
OrderID             object
Date                object
CustomerID          object
Product             object
Quantity             int64
UnitPrice          float64
ShippingAddress     object
PaymentMethod       object
OrderStatus         object
TrackingNumber      object
ItemsInCart          int64
CouponCode          object
ReferralSource      object
TotalPrice         float64
dtype: object

First 5 Rows:

,OrderID,Date,CustomerID,Product,Quantity,UnitPrice,ShippingAddress,PaymentMethod,OrderStatus,TrackingNumber,ItemsInCart,CouponCode,ReferralSource,TotalPrice
0,ORD200000,2023-01-04,C72649,Monitor,5,570.62,928 Main St,Debit Card,Shipped,TRK37947903,7,SAVE10,Instagram,2853.10
1,ORD200001,2024-08-23,C75739,Phone,2,151.35,823 Main St,Online,Shipped,TRK91186779,3,SAVE10,Referral,302.70
2,ORD200002,2024-02-27,C81728,Tablet,5,550.68,512 Main St,Credit Card,Cancelled,TRK42903982,8,FREESHIP,Email,2753.40
3,ORD200003,2023-10-15,C33540,Chair,1,273.19,275 Main St,Debit Card,Returned,TRK62788070,5,SAVE10,Facebook,273.19
4,ORD200004,2025-05-08,C81840,Printer,4,626.01,668 Main St,Online,Delivered,TRK29241424,8,SAVE10,Email,2504.04

Missing Values:
OrderID              0
Date                 0
CustomerID           0
Product              0
Quantity             0
UnitPrice            0
ShippingAddress      0
PaymentMethod        0
OrderStatus          0
TrackingNumber       0
ItemsInCart          0
CouponCode         309
ReferralSource       0
TotalPrice           0
dtype: int64

Duplicate Rows: 0
Duplicates Removed Successfully!

Remaining Missing Values:
OrderID            0
Date               0
CustomerID         0
Product            0
Quantity           0
UnitPrice          0
ShippingAddress    0
PaymentMethod      0
OrderStatus        0
TrackingNumber     0
ItemsInCart        0
CouponCode         0
ReferralSource     0
TotalPrice         0
dtype: int64

Duplicate Rows After Cleaning:
0

Dataset Shape After Cleaning:
(1200, 14)

Updated Data Types:
OrderID                    object
Date               datetime64[ns]
CustomerID                 object
Product                    object
Quantity                    int64
UnitPrice                 float64
ShippingAddress            object
PaymentMethod              object
OrderStatus                object
TrackingNumber             object
ItemsInCart                 int64
CouponCode                 object
ReferralSource             object
TotalPrice                float64
dtype: object

Cleaned dataset saved as 'cleaned_dataset.csv'

,OrderID,Date,CustomerID,Product,Quantity,UnitPrice,ShippingAddress,PaymentMethod,OrderStatus,TrackingNumber,ItemsInCart,CouponCode,ReferralSource,TotalPrice
0,ORD200000,2023-01-04,C72649,Monitor,5,570.62,928 Main St,Debit Card,Shipped,TRK37947903,7,SAVE10,Instagram,2853.10
1,ORD200001,2024-08-23,C75739,Phone,2,151.35,823 Main St,Online,Shipped,TRK91186779,3,SAVE10,Referral,302.70
2,ORD200002,2024-02-27,C81728,Tablet,5,550.68,512 Main St,Credit Card,Cancelled,TRK42903982,8,FREESHIP,Email,2753.40
3,ORD200003,2023-10-15,C33540,Chair,1,273.19,275 Main St,Debit Card,Returned,TRK62788070,5,SAVE10,Facebook,273.19
4,ORD200004,2025-05-08,C81840,Printer,4,626.01,668 Main St,Online,Delivered,TRK29241424,8,SAVE10,Email,2504.04